"""Spider for Jonah Digital "JD Floor Plans" apartment communities.

Communities marketed by Jonah Digital (e.g. many Greystar properties) render
their availability with the *JD Floor Plans* widget -- recognisable by its
``/fp-assets/`` scripts, ``jd-fp-*`` markup and an embedded Engrain SightMap.
The unit list is **not** in the page HTML: the widget fetches it over an XHR to a
``/<page>/_fp-renderable/params:instance=<hash>&action=render&type=listing-chunks``
endpoint, and that ``instance`` hash is generated by the widget's JavaScript at
runtime (it appears nowhere in the served HTML). Because the request cannot be
reproduced without running that JavaScript, this spider renders the page with a
real browser (scrapy-playwright) -- the project's documented last resort.

Rather than re-implement the hash, we let the browser issue the request as it
normally does and capture its response as it arrives. We attach a Playwright
``response`` listener before the page loads, so when the widget's listing-chunks
XHR completes we grab the body straight from it. The response is a ``<chunks>``
document whose ``data-chunk-key="unit-data"`` ``<script>`` holds one JSON object
per available unit.
"""

from __future__ import annotations

import asyncio
import contextlib
import json
import re
from collections.abc import AsyncIterator
from datetime import UTC, datetime
from typing import Any
from urllib.parse import urlparse

import scrapy
from scrapy.http import Response

from apartment_scraper.items import ApartmentItem
from apartment_scraper.utils import to_int, to_number, to_whole_number

# The widget's units request; identified by these two URL fragments.
_CHUNKS_URL_MARKERS = ("_fp-renderable", "listing-chunks")

# The chunks document embeds the per-unit data as a JSON array inside a
# <script ... data-chunk-key="unit-data">[ ... ]</script> element.
_UNIT_DATA_RE = re.compile(r'data-chunk-key="unit-data"[^>]*>(.*?)</script>', re.DOTALL)


def _is_chunks_response(response: Any) -> bool:
    """True for the widget's listing-chunks XHR (the response carrying the units)."""
    return all(marker in response.url for marker in _CHUNKS_URL_MARKERS)


def _bedrooms(value: str | None) -> int | None:
    """Bedroom count as a whole number; a "Studio" counts as 0."""
    if value is None:
        return None
    if "studio" in value.strip().lower():
        return 0
    return to_whole_number(value)


def _available_date(timestamp: Any) -> str | None:
    """Convert the unit's Unix-timestamp availability to an ISO date.

    The feed stores availability as a Unix timestamp in seconds; reading it as
    UTC reproduces the date the site itself displays (its ``price_entity.date``).
    """
    if timestamp in (None, ""):
        return None
    try:
        seconds = int(timestamp)
    except (TypeError, ValueError):
        return None
    return datetime.fromtimestamp(seconds, tz=UTC).date().isoformat()


class JonahSpider(scrapy.Spider):
    name = "jonah"
    # Nothing site-specific is hardcoded: the per-community `community` name and
    # `start_urls` come from communities.toml (via run.py), so this one spider is
    # reusable for every JD Floor Plans community.
    community: str | None = None
    start_urls: list[str] = []

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        if not self.start_urls:
            raise ValueError(
                "JonahSpider has no start_urls. Add the community (name + start_urls) "
                "to communities.toml and run `uv run python run.py` (see README)."
            )
        # Keep the crawl on the domains of the configured start URLs.
        self.allowed_domains = [urlparse(url).netloc for url in self.start_urls]
        # Captured by `_on_response` when the widget's units XHR comes back;
        # `_chunks_ready` lets `parse` wait for it without polling.
        self._chunks_html: str | None = None
        self._chunks_ready = asyncio.Event()

    async def start(self) -> AsyncIterator[Any]:
        for url in self.start_urls:
            yield scrapy.Request(
                url,
                callback=self.parse,
                meta={
                    # Render with a headless browser so the widget fires its XHR;
                    # `_on_response` grabs the units body as it arrives.
                    "playwright": True,
                    "playwright_page_event_handlers": {"response": self._on_response},
                },
            )

    async def _on_response(self, response: Any) -> None:
        """Stash the widget's units XHR body the moment the page receives it."""
        if _is_chunks_response(response):
            self._chunks_html = await response.text()
            self._chunks_ready.set()

    async def parse(self, response: Response, **kwargs: Any) -> AsyncIterator[Any]:
        # Wait until `_on_response` has captured the listing-chunks XHR.
        with contextlib.suppress(TimeoutError):
            await asyncio.wait_for(self._chunks_ready.wait(), timeout=30)
        chunks_html = self._chunks_html

        if not chunks_html:
            self.logger.error("Could not fetch the JD Floor Plans unit data from %s", response.url)
            return

        match = _UNIT_DATA_RE.search(chunks_html)
        if match is None:
            self.logger.error("unit-data chunk not found for %s", response.url)
            return

        community = (self.community or self.name).strip()

        for unit in json.loads(match.group(1)):
            thumbnail = unit.get("thumbnail") or {}
            yield ApartmentItem(
                community=community,
                unit=unit.get("apartment_number"),
                floor_plan=unit.get("floorplan_title"),
                bedrooms=_bedrooms(unit.get("bedrooms")),
                bathrooms=to_number(unit.get("bathrooms")),
                square_feet=to_int(unit.get("square_feet")),
                rent=to_int(unit.get("price") or unit.get("rent_min")),
                available_date=_available_date(unit.get("available_date")),
                url=response.urljoin(unit.get("permalink") or ""),
                floor_plan_image_url=response.urljoin(thumbnail.get("src") or ""),
            )
